name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker run -d -p 443:8080 ${{ secrets.DOCKER_REGISTRY }}/dkawalec76/zse-news-tickers:kezit
